### ISSUE TITLE
Does not compile in Unity 2018.4

### ISSUE THREAD

**Issue by TiliSleepStealer** [vertxxyz/NSelection#5]
NSelection is supposed to work for Unity 2018.3+ but it doesn't.

Main issue is the namespace "UnityEngine.UIElements" does not exist.
Have to replace it with "UnityEngine.Experimental.UIElements".

I suggest an #ifdef block to check for a unity version or discontinue support for Unity 2018.

**Comment by vertxxyz** [comment]
Sorry for the delay. This should be fixed, cheers!
