### ISSUE TITLE
DraggingAdditions not working with 2020.1.0a15

### ISSUE THREAD

**Issue by SugoiDev** [vertxxyz/NSelection#7]
It seems `UnityEditor.GUIView.panel` property is missing somehow.

It's weird because [it is there in the reference source](https://github.com/Unity-Technologies/UnityCsReference/blob/86305f755ec65987bd8de18f3e38bc608adc0ba3/Editor/Mono/GUIView.cs#L51), but, when I decompile on my machine, it is not there.

**Comment by SugoiDev** [comment]
Just pushed a potential fix for this one.

I don't use DraggingAdditions at all, but I decided to try and update it for those on the latest Unity versions that do use it.

**Comment by vertxxyz** [comment]
I've fixed the issue. Thanks for the help with the PR, but there were a few issues with it so I sorted it myself, though your work helped locate the new code! I've also added a define that helps flexibly disabling it in future.
